name: Test Fix Branch

on:
  push:
    branches:
      - 'fix/**'
      - 'hotfix/**'
      - 'test/**'
  pull_request:
    branches:
      - 'fix/**'
      - 'hotfix/**'
      - 'test/**'

jobs:
  test-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
            
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-
        
      - name: Install dependencies
        run: bun install
        
      - name: Install Playwright
        run: bunx playwright install --with-deps
        
      - name: Build project
        run: bun run build:publish
        
      - name: Run lint
        run: bun run lint
        
      - name: Test MCP server startup directly
        run: |
          echo "=== Testing MCP server startup ==="
          echo "CLI file exists:" && ls -la cli.js
          echo "Lib directory:" && ls -la lib/
          echo "Program.js exists:" && ls -la lib/program.js
          echo "Testing server startup..."
          timeout 5s node cli.js --headless --help || echo "Server startup failed with exit code: $?"
        continue-on-error: true
        
      - name: Run single test with debug output
        run: bunx playwright test --project=chrome "tests/batch-execute-basic.spec.ts" --grep "should execute basic navigation batch successfully" --reporter=list
        env:
          DEBUG: 'pw:mcp:*'
          CI: true
        continue-on-error: false